export * from './IndexPage'
export * from './FirstPage'
export * from './Second/SecondPage'
export * from './Second/Pic/PicPage'
export * from './CanDeactivate/CanDeactivatePage'
export * from './Auth/ProtectedByAuthorization'
export * from './Auth/LoginPage'
export * from './Auth/auth.service'
